version: '3.2'

services:
  okta-api:
    container_name: okta-api
    build: ./okta-test-api
    environment: 
      RAILS_ENV: development
      OKTA_ISSUER: https://dev-738834.oktapreview.com/oauth2/ausj9seguriqr0ZDk0h7
      OKTA_CLIENT_ID: 
      PG_URL: okta_api_postgres
      PG_USERNAME: okta_api_user
      PG_PASSWORD: goodnewseveryone
    depends_on: 
      - okta_api_database
    ports:
      - 8080:8080

  rails_app:
    container_name: okta-login-app
    build: ./oktaOmniAuthDeviseSample
    environment: 
      RAILS_ENV: development
      OKTA_REDIRECT_URI: http://localhost:3000/users/auth/oktaoauth/callback
      OKTA_CLIENT_ID: ""
      OKTA_CLIENT_SECRET: ""
      OKTA_ORG: "dev-738834-admin"
      OKTA_DOMAIN: "oktapreview"
      OKTA_URL: "https://dev-738834.oktapreview.com"
      OKTA_ISSUER: "https://dev-738834.oktapreview.com/oauth2/ausj9seguriqr0ZDk0h7"
      OKTA_AUTH_SERVER_ID: "ausj9seguriqr0ZDk0h7"
    depends_on: 
      - okta-api
    ports:
      - 3000:3000
    command: /bin/bash -c "rake db:drop db:create db:migrate && rails s -b 0.0.0.0"

  okta_api_database:
    container_name: okta_api_postgres
    image: postgres:9.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: goodnewseveryone
      POSTGRES_USER: okta_api_user
