version: '3.2'

services:
  okta-api:
    container_name: okta-api
    build: ./okta-test-api
    environment: 
      RAILS_ENV: development
      OKTA_ISSUER: <authorization server>
      OKTA_CLIENT_ID: <application client id from okta>
      PG_URL: okta_api_postgres
      PG_USERNAME: okta_api_user
      PG_PASSWORD: goodnewseveryone
    depends_on: 
      - okta_api_database
    ports:
      - 8080:8080

  rails_app:
    container_name: okta-login-app
    build: ./oktaOmniAuthDeviseSample
    environment: 
      RAILS_ENV: development
    depends_on: 
      - okta-api
    ports:
      - 3000:3000
    command: /bin/bash -c "rake db:drop db:create db:migrate && rails s -b 0.0.0.0"

  okta_api_database:
    container_name: okta_api_postgres
    image: postgres:9.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: goodnewseveryone
      POSTGRES_USER: okta_api_user
